import test from'node:test';import assert from'node:assert/strict';import{createState,tabithaReachedBanner,bannerAction,inspectBannerClue,tabithaReachedSide,sideAction,applyDialogueEffect,inspectPlaque,beginEnding,finishRun}from'../model.js';
test('Tabitha initiates without player input',()=>{const s=createState();assert.equal(s.activity.tabithaInitiated,true);tabithaReachedBanner(s);assert.equal(s.activity.stage,'banner');assert.ok(s.visibleChanges.some(x=>x.kind==='initiative'));});
test('first attempts create different physical and interpersonal state',()=>{const a=createState();tabithaReachedBanner(a);bannerAction(a,'hold_corner');const b=createState();tabithaReachedBanner(b);bannerAction(b,'warn_off');assert.equal(a.banner.heldByPlayer,true);assert.equal(b.banner.warnedOff,true);assert.equal(a.dynamic.workingStyle,'cooperative');assert.equal(b.dynamic.cautious,true);assert.notEqual(a.activity.stage,b.activity.stage);});
test('cautious path reaches side without touching vinyl',()=>{const s=createState();tabithaReachedBanner(s);bannerAction(s,'warn_off');assert.equal(s.banner.touchedByTabitha,false);tabithaReachedSide(s);assert.equal(s.activity.stage,'side');});
test('player discovery changes later physical state and credit',()=>{const s=createState();tabithaReachedBanner(s);bannerAction(s,'phone_torch');inspectBannerClue(s,'read_letters');tabithaReachedSide(s);sideAction(s,'check_rust');assert.equal(s.facts.hingeFoundBy,'player');assert.equal(s.dynamic.playerCredit,1);applyDialogueEffect(s,'confirm_door');assert.equal(s.facts.doorConfirmed,true);});
test('interaction cannot complete through time alone',()=>{const s=createState();assert.equal(s.ended,false);assert.equal(s.activity.resolved,false);});
test('ending preserves conduct-dependent state',()=>{const s=createState();tabithaReachedBanner(s);bannerAction(s,'warn_off');tabithaReachedSide(s);sideAction(s,'check_rust');applyDialogueEffect(s,'confirm_door');inspectPlaque(s);finishRun(s,'keep_looking');assert.equal(s.ended,true);assert.equal(s.dynamic.cautious,true);});

test('spatial continuation begins before the run is finalized',()=>{const s=createState();s.activity.stage='resolution';beginEnding(s,'keep_looking');assert.equal(s.ended,false);assert.equal(s.activity.pendingEnding,'keep_looking');assert.deepEqual(s.tabitha.target,{x:770,y:408});finishRun(s,'keep_looking');assert.equal(s.ended,true);});
