import {SCENES} from './scenario.js';import {applySceneChoice,record} from './model.js';
export function createVNController({vn,titleEl,speakerEl,textEl,choicesEl,portraitEl,runtime,onRunEnd}){let current=null,queue=[],phase='intro';
 function build(id){const base=SCENES[id];if(!base)return null;const scene={...base};if(id==='tabitha_callback'){scene.intro=base.introByPlan[runtime.state.flags.tabithaPlan]||base.introByPlan.default;}else scene.intro=[...(base.intro||[])];if(id==='radio_group'&&runtime.state.flags.privateMotif){scene.intro.unshift(['Tabitha',callbackLine(runtime.state.flags.privateMotif)]);runtime.state.flags.privateContextReincorporated=true;}return scene;}
 function callbackLine(m){if(m==='notice ranking')return 'Do not look now, but the radio table has a laminated cable policy. We may have a contender.';if(m==='laminated menus')return 'Maya has offered crisps. I am still preserving appetite for our extremely regulated breakfast.';if(m==='clear route to door')return 'Door still visible. Architecture remains compliant.';return 'Community resilience has breached containment.';}
 function start(id){const scene=build(id);if(!scene)return;current={id,scene,selected:null};phase='intro';queue=[...scene.intro];runtime.setInputContext('vn');runtime.setPaused(true);vn.hidden=false;titleEl.textContent=scene.title;portraitEl.textContent=scene.portraits.map(x=>x.toUpperCase()).join(' · ');advance();record(runtime.state,'vn_open',{id});}
 function advance(){if(!current)return;if(queue.length){const [sp,tx]=queue.shift();speakerEl.textContent=sp;textEl.textContent=tx;choicesEl.replaceChildren(makeButton(queue.length||phase==='response'?'Continue':'Continue',advance,'continue'));return;}if(phase==='intro'){speakerEl.textContent='You';textEl.textContent=current.scene.question;choicesEl.replaceChildren(...current.scene.choices.map((c,i)=>makeButton(`${i+1}. ${c.text}`,()=>select(c),'' ,c.id)));return;}close();}
 function select(choice){current.selected=choice;const responses=applySceneChoice(runtime.state,current.id,choice);runtime.afterWorldChange();phase='response';queue=[...responses];record(runtime.state,'vn_choice',{sceneId:current.id,choiceId:choice.id});if(queue.length)advance();else close();}
 function close({cancelled=false}={}){if(!current)return;const ended=runtime.state.ended;const id=current.id;vn.hidden=true;runtime.setPaused(false);runtime.setInputContext('world');current=null;queue=[];if(cancelled)record(runtime.state,'vn_cancelled',{sceneId:id});runtime.afterWorldChange();if(ended)onRunEnd();}
 function makeButton(text,fn,cls='',id=null){const b=document.createElement('button');b.textContent=text;b.className=cls;if(id)b.dataset.choice=id;b.onclick=fn;return b;}
 function handleKey(key){if(!current)return false;if(key==='escape'){close({cancelled:true});return true;}if(/^[1-4]$/.test(key)){const b=choicesEl.querySelectorAll('button[data-choice]')[Number(key)-1];if(b){b.click();return true;}}if((key==='enter'||key===' ')&&choicesEl.children.length===1&&choicesEl.firstElementChild.classList.contains('continue')){choicesEl.firstElementChild.click();return true;}return false;}
 return{start,handleKey,close,get active(){return Boolean(current);}};}
