import {WORLD,CHARACTERS} from './scenario.js';import {createState,getAvailableInteractions,shareNotice,observeRadio,finishRun,record} from './model.js';
export function createWorldRuntime({canvas,hudZone,hudTime,promptEl,noticeEl,situationEl}){const ctx=canvas.getContext('2d');let state,keys,inputContext='world',paused=false,current=0,sceneHandler=()=>{},endHandler=()=>{},noticeTimer=null;const npc={};
 function reset(){state=createState();state.runId=globalThis.crypto?.randomUUID?.()||`run-${Date.now()}`;for(const [id,c]of Object.entries(CHARACTERS))npc[id]={...state.characters[id]};keys=new Set();current=0;inputContext='world';paused=false;showNotice('Friday, 19:03. You arrived with Tabitha. Maya and Alex are already inside.',4400);setSituation('The hall is open. Nothing is demanding you yet.');record(state,'run_started');}
 function showNotice(text,ms=3200){noticeEl.textContent=text;noticeEl.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>noticeEl.classList.remove('visible'),ms);}
 function setSituation(text){situationEl.textContent=text||'';}
 function zoneAt(x,y){for(const z of Object.values(WORLD.zones))if(x>=z.x&&x<=z.x+z.w&&y>=z.y&&y<=z.y+z.h)return z.id;return state.player.zone;}
 function collides(x,y){const r=14;if(x<38||y<38||x>WORLD.width-38||y>WORLD.height-38)return true;return WORLD.obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);}
 function setKey(k,d){if(inputContext!=='world')return;if(d)keys.add(k);else keys.delete(k);}function clearKeys(){keys.clear();}function setInputContext(v){inputContext=v;if(v!=='world')clearKeys();}function setPaused(v){paused=v;}function setSceneHandler(fn){sceneHandler=fn;}function setEndHandler(fn){endHandler=fn;}
 function move(dt){if(paused||inputContext!=='world')return;let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(!dx&&!dy)return;const l=Math.hypot(dx,dy);dx/=l;dy/=l;state.player.facing={x:dx,y:dy};const nx=state.player.x+dx*190*dt,ny=state.player.y+dy*190*dt;if(!collides(nx,state.player.y))state.player.x=nx;if(!collides(state.player.x,ny))state.player.y=ny;state.player.zone=zoneAt(state.player.x,state.player.y);}
 function moveNpc(p,dt){if(!p.visible||!p.target)return;const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy);if(d<2)return;p.x+=(dx/d)*Math.min(d,100*dt);p.y+=(dy/d)*Math.min(d,100*dt);}
 function syncNpc(){for(const [id,s]of Object.entries(state.characters)){if(!npc[id])npc[id]={...s};npc[id].visible=s.visible;npc[id].mood=s.mood;npc[id].target={...(s.target||{x:s.x,y:s.y})};if(Math.abs(npc[id].x-s.x)>220||Math.abs(npc[id].y-s.y)>220){npc[id].x=s.x;npc[id].y=s.y;}}}
 function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}function nearPoint(p,r=110){return distance(state.player,p)<=r;}function nearNpc(id,r=130){return npc[id]?.visible&&distance(state.player,npc[id])<=r;}
 function candidates(){const ids=getAvailableInteractions(state,state.player.zone),out=[];for(const id of ids){if(id==='tabitha_opening'&&nearNpc('tabitha',120))out.push(x(id,'Spend a moment with Tabitha'));else if(id==='noticeboard'&&nearPoint(WORLD.points.noticeboard,120))out.push(x(id,'Look at the noticeboard with Tabitha'));else if(id==='tabitha_private'&&nearNpc('tabitha',150))out.push(x(id,'Talk with Tabitha'));else if(id==='tabitha_callback'&&nearNpc('tabitha',170))out.push(x(id,'Sit on the low wall with Tabitha'));else if(id==='radio_group'&&nearNpc('maya',180))out.push(x(id,'Join Maya and Alex'));else if(id==='priya_private'&&nearNpc('priya',160))out.push(x(id,'Talk with Priya'));else if(id==='mixed_story'&&nearNpc('maya',180))out.push(x(id,'Stay for the group story'));else if(id==='closing'&&nearNpc('elliot',220))out.push(x(id,'Listen to Elliot and Maya'));else if(id==='observe_radio'&&nearNpc('maya',210))out.push(x(id,'Listen from the edge'));else if(id.startsWith('leave_')&&nearPoint(WORLD.points.exit,120))out.push(x(id,id==='leave_solo'?'Head home':id==='leave_priya'?'Go for chips with Priya':'Go on with Maya and the radio crowd'));}return out;}
 function x(id,label){return{id,label};}
 function cycleTarget(){const a=candidates();if(!a.length)return;current=(current+1)%a.length;renderPrompt();}
 function interact(){const a=candidates();if(!a.length)return;const it=a[Math.min(current,a.length-1)];if(it.id==='noticeboard'){shareNotice(state);state.characters.tabitha.target={x:195,y:390};showNotice('Tabitha: “Social Connection Drop-In — booking essential.”  You both stare at it for a second.');afterWorldChange();return;}if(it.id==='observe_radio'){observeRadio(state);showNotice('Maya: “Can a jingle be administratively loud?”  Alex: “Apparently yes.”');afterWorldChange();return;}if(it.id==='leave_solo'){finishRun(state,{id:'end_solo',text:'You head home alone.',tags:['left_solo']});afterWorldChange();endHandler();return;}if(it.id==='leave_priya'){finishRun(state,{id:'end_priya',text:'You go for chips with Priya.',tags:['went_chips_priya']});afterWorldChange();endHandler();return;}if(it.id==='leave_maya'){finishRun(state,{id:'end_maya',text:'You continue with Maya and the radio crowd.',tags:['joined_afterparty']});afterWorldChange();endHandler();return;}sceneHandler(it.id);}
 function afterWorldChange(){syncNpc();const v=state.visibleChanges.at(-1);if(v)showNotice(v.detail,3800);if(state.flags.tabithaPrivateDone&&!state.flags.tabithaCallbackDone)setSituation('Something specific has formed between you and Tabitha. She has drifted round the side rather than disappearing into the room.');else if(state.flags.noticeShared&&!state.flags.tabithaPrivateDone)setSituation('The noticeboard joke has become something the two of you are sharing, not just scenery.');else if(state.flags.radioGroupTouched)setSituation('The radio corner is active; you can remain at the edge, join in, or walk away.');else if(state.flags.priyaArrived&&!state.flags.priyaSettled)setSituation('Priya has arrived. She can find her own way in if you leave her to it.');else setSituation('The evening continues around whatever company you choose.');}
 function renderPrompt(){const a=candidates();if(current>=a.length)current=0;promptEl.textContent=a.length?`E — ${a[current].label}`:'';}
 function tick(dt){move(dt);syncNpc();for(const p of Object.values(npc))moveNpc(p,dt);renderPrompt();hudZone.textContent=WORLD.zones[state.player.zone]?.label||state.player.zone;hudTime.textContent=state.fictionalTime;}
 function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const g=ctx.createLinearGradient(0,0,900,520);g.addColorStop(0,'#aeb7aa');g.addColorStop(1,'#d8c7a9');ctx.fillStyle=g;ctx.fillRect(0,0,900,520);zone(WORLD.zones.main,'#eadfcf','#8c7e6b');zone(WORLD.zones.radio,'#d2c3af','#806d59');zone(WORLD.zones.forecourt,'#b8c1b1','#74806f');zone(WORLD.zones.side,'#aab6a0','#6e7a68');ctx.fillStyle='#6a6258';ctx.font='13px system-ui';ctx.fillText('COMMUNITY HALL',250,82);ctx.fillText('forecourt',30,338);ctx.fillText('side yard',680,245);ctx.fillText('radio corner',490,107);box(312,190,118,58,'#ad8763');box(300,320,82,38,'#96735a');box(496,145,105,28,'#6d6257');box(690,390,92,22,'#88735b');ctx.fillStyle='#705e4d';ctx.fillRect(WORLD.points.noticeboard.x-18,WORLD.points.noticeboard.y-32,36,54);ctx.fillStyle='#eee4cb';ctx.fillRect(WORLD.points.noticeboard.x-14,WORLD.points.noticeboard.y-28,28,46);ctx.fillStyle='#403b35';ctx.font='9px system-ui';ctx.textAlign='center';ctx.fillText('NOTICE',WORLD.points.noticeboard.x,WORLD.points.noticeboard.y-3);ctx.textAlign='start';for(const [id,p]of Object.entries(npc)){if(!p.visible)continue;const c=CHARACTERS[id];ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.fillStyle=c.color;ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#fffaf2';ctx.stroke();ctx.fillStyle='#292622';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText(c.short,p.x,p.y+4);ctx.textAlign='start';}ctx.beginPath();ctx.arc(state.player.x,state.player.y,15,0,Math.PI*2);ctx.fillStyle='#272522';ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='#fff';ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText('YOU',state.player.x,state.player.y+4);ctx.textAlign='start';}
 function zone(z,fill,stroke){ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.fillRect(z.x,z.y,z.w,z.h);ctx.strokeRect(z.x,z.y,z.w,z.h);}function box(x,y,w,h,fill){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);}
 reset();return{get state(){return state},tick,draw,interact,cycleTarget,setKey,clearKeys,setInputContext,setPaused,setSceneHandler,setEndHandler,showNotice,afterWorldChange,reset};}
