import { WORLD, CHARACTERS } from './scenario.js';
import { createState, record, observeBeat, getAvailableInteractions } from './model.js';

const anchors={tabitha_arrival:s=>s.characters.tabitha,tabitha_side:s=>s.characters.tabitha,radio_group:s=>({x:(s.characters.maya.x+s.characters.alex.x)/2,y:(s.characters.maya.y+s.characters.alex.y)/2}),priya_greeting:s=>s.characters.priya,priya_private:s=>s.characters.priya,mixed_story:s=>({x:545,y:250}),closing:s=>s.characters.elliot,quiet_linger:()=>({x:185,y:455}),room_linger:()=>({x:438,y:285}),ending:()=>({x:70,y:425})};
const labels={tabitha_arrival:'Spend a moment with Tabitha',tabitha_side:'Stay somewhere quieter with Tabitha',radio_group:'Join Maya and Alex',priya_greeting:'Talk to Priya',priya_private:'Talk with Priya',mixed_story:'Join the story being told',closing:'Listen to Elliot and Maya',quiet_linger:'Stay here together a while',room_linger:'Stay and listen a while',ending:'Head out / decide where next'};

export function createWorldRuntime({canvas,hudRoom,hudTime,promptEl,noticeEl,situationEl}){
 const ctx=canvas.getContext('2d');let state,keys,inputContext,sceneHandler=()=>{},currentTarget=null,lastVisibleIndex=0,noticeTimer=null,ambientTimer=0;
 function reset(){state=createState();state.runId=globalThis.crypto?.randomUUID?.()||`run-${Date.now()}`;keys=new Set();inputContext='world';currentTarget=null;lastVisibleIndex=0;ambientTimer=0;showNotice('Friday, 19:03. You came here with Tabitha. Nothing requires you to go inside immediately.',4800);record(state,'run_started',{intent:'open social evening'});}
 function setKey(k,d){if(inputContext!=='world')return;if(d)keys.add(k);else keys.delete(k)}function clearKeys(){keys.clear()}function setInputContext(v){inputContext=v;if(v!=='world')clearKeys()}function setPaused(v){state.paused=v}function setSceneHandler(fn){sceneHandler=fn}function showNotice(text,ms=3000){noticeEl.textContent=text;noticeEl.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>noticeEl.classList.remove('visible'),ms)}
 function zoneAt(x,y){for(const z of Object.values(WORLD.zones))if(x>=z.x&&x<=z.x+z.w&&y>=z.y&&y<=z.y+z.h)return z.id;return'forecourt'}
 function collides(x,y){if(x<18||y<18||x>WORLD.width-18||y>WORLD.height-18)return true;return WORLD.obstacles.some(o=>x+14>o.x&&x-14<o.x+o.w&&y+14>o.y&&y-14<o.y+o.h)}
 function movePlayer(dt){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(!dx&&!dy)return;const l=Math.hypot(dx,dy);dx/=l;dy/=l;state.player.facing={x:dx,y:dy};const nx=state.player.x+dx*190*dt,ny=state.player.y+dy*190*dt;if(!collides(nx,state.player.y))state.player.x=nx;if(!collides(state.player.x,ny))state.player.y=ny;state.player.zone=zoneAt(state.player.x,state.player.y)}
 function moveNpc(p,dt,speed=90){if(!p.visible||!p.target)return;const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy);if(d<2)return;p.x+=(dx/d)*Math.min(d,speed*dt);p.y+=(dy/d)*Math.min(d,speed*dt)}
 function updateCompanion(){const t=state.characters.tabitha;if((state.player.zone==='main'||state.player.zone==='radio')&&state.beat===0&&!state.flags.tabithaArrivalDone&&t.x<260)t.target={x:445,y:300};if(state.flags.tabithaCompanion&&t.mood!=='annoyed'){const allowed=['forecourt','side','main'];if(allowed.includes(state.player.zone))t.target={x:state.player.x-38,y:state.player.y+18}}const p=state.characters.priya;if(p.mood==='quiet company'&&['forecourt','main'].includes(state.player.zone))p.target={x:state.player.x+42,y:state.player.y+20}}
 function speak(id,text,dur=4){const p=state.characters[id];if(!p)return;p.speech=text;p.speechUntil=performance.now()/1000+dur;record(state,'ambient_speech',{speaker:id,text})}
 function ambient(dt){ambientTimer-=dt;if(ambientTimer>0)return;ambientTimer=5.5;const z=state.player.zone;if((z==='main'||z==='radio')&&state.flags.priyaSettled&&state.flags.radioGroupTouched)speak(state.beat%2?'maya':'alex',state.beat%2?'No, the ident cannot be “more municipal”.':'I am deleting the file called FINAL_FINAL_3.');else if(z==='main'||z==='radio')speak(state.beat%2?'maya':'alex',state.beat%2?'If it peaks red again, believe less strongly in audio engineering.':'I moved the cable six inches. We are innovating.');else if(z==='forecourt'&&state.flags.priyaArrived&&!state.flags.priyaSettled)speak('priya','I am deciding whether that sign is a warning or branding.');else if((z==='forecourt'||z==='side')&&state.flags.tabithaCompanion)speak('tabitha',state.beat%2?'This is already better than being indoors.':'I can hear Maya from here. Somehow.')}
 function interactionCandidates(){const ids=getAvailableInteractions(state,state.player.zone),list=[];for(const id of ids){const a=anchors[id]?.(state);if(!a)continue;if(id==='mixed_story'){const t=state.characters.tabitha;if(Math.hypot(t.x-a.x,t.y-a.y)>190)continue}const d=Math.hypot(state.player.x-a.x,state.player.y-a.y);const range=id==='room_linger'?150:id==='quiet_linger'?140:id==='ending'?125:120;if(d<=range)list.push({id,x:a.x,y:a.y,d,range,label:labels[id]})}list.sort((a,b)=>score(a)-score(b));return list}
 function score(a){const dx=a.x-state.player.x,dy=a.y-state.player.y,d=Math.max(1,Math.hypot(dx,dy));const facing=(dx/d)*state.player.facing.x+(dy/d)*state.player.facing.y;return a.d-facing*28}
 function chooseTarget(){const c=interactionCandidates();if(!c.length){currentTarget=null;return}if(currentTarget&&c.some(x=>x.id===currentTarget))return;currentTarget=c[0].id}function cycleTarget(){const c=interactionCandidates();if(!c.length){currentTarget=null;return}const i=Math.max(-1,c.findIndex(x=>x.id===currentTarget));currentTarget=c[(i+1)%c.length].id}
 function interact(){const c=interactionCandidates(),target=c.find(x=>x.id===currentTarget)||c[0];if(!target)return;record(state,'interaction',{id:target.id,zone:state.player.zone});if(target.id==='quiet_linger'||target.id==='room_linger'){observeBeat(state,target.id);if(target.id==='quiet_linger')speak('tabitha','This counts as doing something. We are standing somewhere on purpose.');else speak('maya','You can just listen, by the way. We are perfectly capable of filling the air ourselves.');syncVisibleChanges();return}sceneHandler(target.id)}
 function syncVisibleChanges(){while(lastVisibleIndex<state.visibleChanges.length){const change=state.visibleChanges[lastVisibleIndex++];showNotice(change.detail,change.kind==='arrival'?4300:3000)}}
 function situationText(){if(state.ended)return'The evening is over.';if(state.player.zone==='forecourt'){if(state.flags.priyaArrived&&!state.flags.priyaSettled)return'Tabitha is nearby. Priya has just arrived. The hall is behind you.';if(state.flags.tabithaCompanion)return'You are outside with Tabitha. The radio night continues inside.';return'The forecourt is quiet enough to choose whether to go in.'}if(state.player.zone==='side')return state.characters.tabitha.mood==='annoyed'?'Tabitha has stepped away from the group.':'The side yard is quieter than the main room.';if(state.flags.closureActive)return'Elliot is closing part of the hall. Nobody is waiting for you to fix it.';if(state.flags.priyaSettled)return'Maya, Alex and Priya have found a rhythm. You can join, listen or leave.';return'Maya and Alex are doing the radio night. You can join or simply be here.'}
 function tick(dt){if(state.paused)return;movePlayer(dt);updateCompanion();for(const p of Object.values(state.characters))moveNpc(p,dt);chooseTarget();ambient(dt);syncVisibleChanges()}
 function draw(){canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;ctx.setTransform(canvas.width/WORLD.width,0,0,canvas.height/WORLD.height,0,0);const g=ctx.createLinearGradient(0,0,900,520);g.addColorStop(0,'#aeb8a8');g.addColorStop(1,'#d6c4a8');ctx.fillStyle=g;ctx.fillRect(0,0,900,520);drawZone(WORLD.zones.main,'#e7dccb','#8f816f');drawZone(WORLD.zones.radio,'#d4c5b3','#7f6f5e');drawZone(WORLD.zones.forecourt,'#b9c0b2','#718074');drawZone(WORLD.zones.side,'#aab6a0','#6d7d69');ctx.fillStyle='#625b52';ctx.font='13px system-ui';ctx.fillText('COMMUNITY HALL',260,80);ctx.fillText('radio corner',490,106);ctx.fillText('forecourt',32,338);ctx.fillText('side yard',684,248);for(const o of WORLD.obstacles){ctx.fillStyle='#8d765f';ctx.fillRect(o.x,o.y,o.w,o.h)}for(const[id,p]of Object.entries(state.characters)){if(!p.visible)continue;drawPerson(id,p)}ctx.beginPath();ctx.arc(state.player.x,state.player.y,15,0,Math.PI*2);ctx.fillStyle='#20211e';ctx.fill();ctx.strokeStyle='#f5efe5';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText('YOU',state.player.x,state.player.y+4);ctx.textAlign='start';const c=interactionCandidates(),target=c.find(x=>x.id===currentTarget)||c[0];if(target){ctx.beginPath();ctx.arc(target.x,target.y,29,0,Math.PI*2);ctx.strokeStyle='#f0e2a7';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.stroke();ctx.setLineDash([]);promptEl.textContent=`E — ${target.label}`}else promptEl.textContent='';hudRoom.textContent=WORLD.zones[state.player.zone]?.label||state.player.zone;hudTime.textContent=state.fictionalTime;situationEl.textContent=situationText()}
 function drawZone(z,fill,stroke){ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.fillRect(z.x,z.y,z.w,z.h);ctx.strokeRect(z.x,z.y,z.w,z.h)}
 function drawPerson(id,p){const c=CHARACTERS[id];ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.fillStyle=c.color;ctx.fill();ctx.strokeStyle='#fffaf2';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#282522';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText(c.short,p.x,p.y+4);ctx.textAlign='start';if(p.speech&&p.speechUntil>performance.now()/1000){const text=p.speech,max=235,x=Math.max(10,Math.min(WORLD.width-max-10,p.x-max/2)),y=Math.max(8,p.y-72);ctx.font='12px system-ui';const lines=wrap(text,32),h=18+lines.length*15;ctx.fillStyle='#151713e8';ctx.fillRect(x,y,max,h);ctx.fillStyle='#eee8dc';lines.forEach((ln,i)=>ctx.fillText(ln,x+10,y+18+i*15))}}
 function wrap(text,n){const words=text.split(' '),out=[];let line='';for(const w of words){if((line+' '+w).trim().length>n){out.push(line);line=w}else line=(line+' '+w).trim()}if(line)out.push(line);return out}
 reset();return{get state(){return state},reset,tick,draw,setKey,clearKeys,setInputContext,setPaused,setSceneHandler,interact,cycleTarget,showNotice,syncVisibleChanges};
}
