import test from 'node:test';
import assert from 'node:assert/strict';
import { createState, applySceneChoice, observeBeat, getAvailableInteractions, getEndingChoices, finishRun } from '../model.js';
import { SCENES } from '../scenario.js';
const choice=(scene,id)=>SCENES[scene].choices.find(c=>c.id===id);

test('quiet route is available from opening without group content or immediate social intrusion',()=>{const s=createState();assert.ok(getAvailableInteractions(s,'forecourt').includes('tabitha_arrival'));applySceneChoice(s,'tabitha_arrival',choice('tabitha_arrival','tabitha_stay'));assert.ok(getAvailableInteractions(s,'forecourt').includes('quiet_linger'));assert.ok(getAvailableInteractions(s,'side').includes('tabitha_side'));assert.equal(s.flags.radioGroupSceneDone,false);assert.equal(s.flags.priyaArrived,false);});
test('quiet player can reach ending without any group scene',()=>{const s=createState();applySceneChoice(s,'tabitha_arrival',choice('tabitha_arrival','tabitha_stay'));observeBeat(s,'quiet_linger');assert.equal(s.flags.priyaArrived,true);assert.ok(getAvailableInteractions(s,'forecourt').includes('ending'));assert.equal(s.flags.radioGroupSceneDone,false);const end=getEndingChoices(s).find(x=>x.id==='end_tabitha');finishRun(s,end);assert.equal(s.ended,true);assert.ok(s.residue.some(r=>r.id==='tabitha_photo'));});
test('social player gets earlier world activity by entering the social room',()=>{const s=createState();s.player.zone='main';applySceneChoice(s,'radio_group',choice('radio_group','group_joke'));assert.equal(s.flags.priyaArrived,true);assert.equal(s.flags.priyaSettled,false);observeBeat(s,'room_linger');assert.equal(s.flags.priyaSettled,true);assert.ok(getAvailableInteractions(s,'main').includes('mixed_story'));});
test('Priya settles without protagonist shepherding one meaningful beat after arriving',()=>{const s=createState();s.player.zone='main';observeBeat(s,'room_linger');assert.equal(s.flags.priyaArrived,true);assert.equal(s.flags.priyaSettled,false);observeBeat(s,'second_observe');assert.equal(s.flags.priyaSettled,true);assert.equal(s.flags.priyaGreetingDone,false);});
test('joining a group does not create a completion gate for leaving',()=>{const s=createState();s.player.zone='main';applySceneChoice(s,'radio_group',choice('radio_group','group_listen'));observeBeat(s,'room_linger');assert.ok(getAvailableInteractions(s,'forecourt').includes('ending'));assert.equal(s.flags.mixedStoryDone,false);});
test('meaningful situational choices create immediate visible state',()=>{const cases=[['tabitha_arrival','tabitha_stay'],['radio_group','group_tabitha'],['priya_greeting','priya_space'],['mixed_story','story_full']];for(const[scene,id]of cases){const s=createState();if(scene==='priya_greeting'){s.flags.priyaArrived=true;s.flags.priyaArrivalBeat=0;s.characters.priya.visible=true;}if(scene==='mixed_story'){s.flags.priyaSettled=true;s.flags.radioGroupTouched=true;}const before=s.visibleChanges.length;applySceneChoice(s,scene,choice(scene,id));assert.ok(s.visibleChanges.length>before,`${scene}/${id} should create visible acknowledgement`);}});
test('public boundary choice changes Tabitha immediately and persists into interpretation',()=>{const s=createState();s.flags.priyaSettled=true;s.flags.radioGroupTouched=true;applySceneChoice(s,'mixed_story',choice('mixed_story','story_full'));assert.equal(s.characters.tabitha.mood,'annoyed');assert.deepEqual(s.characters.tabitha.target,{x:742,y:350});observeBeat(s,'room_linger');const end=getEndingChoices(s).find(x=>x.id==='end_solo');finishRun(s,end);assert.equal(s.interpretations.tabitha.read,'made_me_the_story');});
