import test from 'node:test';
import assert from 'node:assert/strict';
import { createState, applySceneChoice, observeBeat, getEndingChoices, finishRun } from '../model.js';
import { SCENES } from '../scenario.js';
const ch=(s,id)=>SCENES[s].choices.find(x=>x.id===id);const end=(s,id)=>getEndingChoices(s).find(x=>x.id===id);

test('preflight persona: quiet player can make the evening mostly Tabitha 1:1',()=>{const s=createState();applySceneChoice(s,'tabitha_arrival',ch('tabitha_arrival','tabitha_stay'));assert.equal(s.flags.priyaArrived,false);observeBeat(s,'quiet_linger');applySceneChoice(s,'tabitha_side',ch('tabitha_side','side_stay'));finishRun(s,end(s,'end_tabitha'));assert.equal(s.ended,true);assert.deepEqual(s.seenScenes,['tabitha_arrival','tabitha_side']);assert.equal(s.flags.radioGroupSceneDone,false);assert.equal(s.flags.mixedStoryDone,false);assert.equal(s.interpretations.tabitha.read,'comfortable_quiet_company');});
test('preflight persona: social player can choose groups without making them mandatory',()=>{const s=createState();s.player.zone='main';applySceneChoice(s,'radio_group',ch('radio_group','group_joke'));observeBeat(s,'room_linger');applySceneChoice(s,'mixed_story',ch('mixed_story','story_safe'));observeBeat(s,'room_linger');finishRun(s,end(s,'end_maya'));assert.equal(s.ended,true);assert.ok(s.seenScenes.includes('radio_group'));assert.ok(s.seenScenes.includes('mixed_story'));assert.equal(s.interpretations.maya.read,'becoming_part_of_the_radio_crowd');});
test('preflight persona: observer can complete with zero VN scenes',()=>{const s=createState();s.player.zone='main';observeBeat(s,'room_linger');s.player.zone='forecourt';observeBeat(s,'quiet_linger');finishRun(s,end(s,'end_solo'));assert.equal(s.seenScenes.length,0);assert.equal(s.ended,true);});
test('preflight persona: Priya-selective player can avoid radio group',()=>{const s=createState();applySceneChoice(s,'tabitha_arrival',ch('tabitha_arrival','tabitha_tease'));observeBeat(s,'quiet_linger');assert.equal(s.flags.priyaArrived,true);applySceneChoice(s,'priya_greeting',ch('priya_greeting','priya_quiet'));finishRun(s,end(s,'end_priya'));assert.equal(s.flags.radioGroupSceneDone,false);assert.equal(s.flags.mixedStoryDone,false);assert.equal(s.interpretations.priya.read,'chose_more_time_with_me');});
test('preflight persona: uninterested player can leave before closure or group content',()=>{const s=createState();observeBeat(s,'quiet_linger');s.player.zone='main';observeBeat(s,'room_linger');assert.equal(s.flags.closureActive,false);finishRun(s,end(s,'end_solo'));assert.equal(s.ended,true);assert.equal(s.seenScenes.length,0);});
